package mihon.gradle.tasks

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.OutputFile
import org.gradle.api.tasks.TaskAction
import org.gradle.process.ExecOperations
import java.io.ByteArrayOutputStream
import java.time.Instant
import java.time.LocalDateTime
import java.time.ZoneOffset
import java.time.format.DateTimeFormatter
import javax.inject.Inject

private val BUILD_TIME_FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss'Z'")

abstract class GenerateBuildConstantsTask @Inject constructor(
    private val execOperations: ExecOperations,
) : DefaultTask() {
    @get:OutputDirectory
    abstract val outputDir: DirectoryProperty

    @get:Input
    abstract val packageName: Property<String>

    @get:Input
    abstract val useLatestCommitTime: Property<Boolean>

    @TaskAction
    fun generate() {
        val commitCountValue = getCommitCount(execOperations)
        val commitShaValue = getGitSha(execOperations)
        val buildTimeValue = getBuildTime(execOperations, useLatestCommitTime.get())

        val packageName = packageName.get()
        val className = "BuildConstants"

        val fileContent = """
            // Generated by Gradle. Do not edit.
            package $packageName

            object $className {
                const val COMMIT_COUNT: String = "$commitCountValue"
                const val COMMIT_SHA: String = "$commitShaValue"
                const val BUILD_TIME: String = "$buildTimeValue"
            }
        """.trimIndent()

        val packagePath = packageName.replace('.', '/')
        val outputFile = outputDir.file("$packagePath/$className.kt").get().asFile
        outputFile.parentFile.mkdirs()
        outputFile.writeText(fileContent)
    }

    /**
     * @param execOperations: ExecOperations instance to run Git commands.
     * @param useLatestCommitTime If `true`, the build time is based on the timestamp of the last Git commit;
     *                          otherwise, the current time is used. Both are in UTC.
     * @return A formatted string representing the build time. The format used is defined by [BUILD_TIME_FORMATTER].
     */
    fun getBuildTime(execOperations: ExecOperations, useLatestCommitTime: Boolean): String {
        return if (useLatestCommitTime) {
            try {
                val epoch = runCommand(execOperations, "git log -1 --format=%ct").toLong()
                Instant.ofEpochSecond(epoch).atOffset(ZoneOffset.UTC).format(BUILD_TIME_FORMATTER)
            } catch (_: Exception) {
                LocalDateTime.now(ZoneOffset.UTC).format(BUILD_TIME_FORMATTER)
            }
        } else {
            LocalDateTime.now(ZoneOffset.UTC).format(BUILD_TIME_FORMATTER)
        }
    }
}

abstract class ComputeGitHashTask @Inject constructor(
    private val execOperations: ExecOperations,
) : DefaultTask() {
    @get:OutputFile
    abstract val gitHashFile: RegularFileProperty

    @TaskAction
    fun compute() {
        gitHashFile.get().asFile.writeText(getCommitCount(execOperations))
    }
}

private fun getCommitCount(execOperations: ExecOperations): String = try {
    runCommand(execOperations, "git rev-list --count HEAD")
} catch (e: Exception) {
    println("Error getting commit count: ${e.message}")
    "0"
}

private fun getGitSha(execOperations: ExecOperations): String = try {
    runCommand(execOperations, "git rev-parse --short HEAD")
} catch (e: Exception) {
    println("Error getting git sha: ${e.message}")
    "0"
}

/**
 * The output of this function must be wrapped with try-catch when called.
 * The reason is that when running this in Android Studio in Mac with xcode uninstalled
 * and kotlin multiplatform plugin installed,
 * it will throw an exception causing the build to fail.
 * But building it with gradle in terminal at Mac will work just fine.
 */
private fun runCommand(execOperations: ExecOperations, command: String): String {
    println("Running command: $command")
    val output = ByteArrayOutputStream()
    execOperations.exec {
        commandLine = command.split(" ")
        standardOutput = output
    }
    println("Command output: ${output.toString().trim()}")
    return output.toString().trim()
}
