query AniListSearchManga($search: String!) {
  Page (perPage: 50) {
    media(search: $search, type: MANGA, format_not_in: [NOVEL]) {
      id
      staff {
        edges {
          role
          id
          node {
            name {
              full
              userPreferred
              native
            }
          }
        }
      }
      title {
        userPreferred
      }
      coverImage {
        large
      }
      format
      countryOfOrigin
      status
      chapters
      description
      startDate {
        year
        month
        day
      }
      averageScore
    }
  }
}
