name: Mihon Nightly

on:
  workflow_dispatch:
    inputs:
      git_ref:
        description: 'Branch, tag, or commit SHA to build'
        required: false
        default: 'main'
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ inputs.git_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build-nightly:
    name: Build Mihon Nightly
    runs-on: 'ubuntu-24.04'

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.git_ref || github.ref }}

      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version-file: .github/.java-version
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0

      - name: Build Nightly APKs
        run: ./gradlew assembleNightly -Pinclude-telemetry -Penable-updater

      - name: Upload Nightly APKs
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: Mihon-Nightly-${{ github.sha }}
          path: app/build/outputs/apk/nightly/*.apk
